spring:
  datasource:
    url: jdbc:mysql://memento-mysql-local:3306/memento
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: memento-redis-local
      port: 6379