spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      host: memento-redis-prod
      port: 6379

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql: off

minio:
  url: ${MINIO_URL}
  public-url: ${MINIO_PUBLIC_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  buckets:
    post: ${POST_BUCKET}
    voice: ${VOICE_BUCKET}
    emoji: ${EMOJI_BUCKET}
    profile-image: ${PROFILE_IMAGE_BUCKET}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: http://memento.ai.kr/landing
  kauth-host: https://kauth.kakao.com
  kapi-host: https://kapi.kakao.com

jwt:
  grant-type: Bearer
  secret: ${JWT_SECRET}
  access-token-expire-time: 3600000
  refresh-token-expire-time: 604800000
  temp-time: 1800000

file:
  upload:
    voice:
      max-size-bytes: 10485760  # 10MB
      allowed-types:
        - audio/mpeg
        - audio/wav
        - audio/mp4
        - audio/aac
        - audio/ogg
        - audio/webm
    image:
      max-size-bytes: 5242880   # 5MB
      allowed-types:
        - image/jpeg
        - image/jpg
        - image/png
        - image/gif
        - image/webp
    post:
      max-total-size-bytes: 52428800  # 50MB
      max-file-count: 10