spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://memento-mysql-dev:3306/memento
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      host: memento-redis-dev
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

minio:
    url: ${MINIO_URL}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    bucket: ${MINIO_BUCKET_NAME}

file:
  upload:
    voice:
      max-size-bytes: 10485760  # 10MB
      allowed-types:
        - audio/mpeg
        - audio/wav
        - audio/mp4
        - audio/aac
        - audio/ogg
        - audio/webm
    image:
      max-size-bytes: 5242880   # 5MB
      allowed-types:
        - image/jpeg
        - image/jpg
        - image/png
        - image/gif
        - image/webp
    post:
      max-total-size-bytes: 52428800  # 50MB
      max-file-count: 10