services:
  memento-mysql-dev:
    image: mysql:8.0
    container_name: memento-mysql-dev
    restart: always
    env_file:
      - ../env/.env.dev
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3316:3306"
    volumes:
      - ../env/.env.dev:/env/.env.dev
      - ../db/mysql/dev:/docker-entrypoint-initdb.d
      - mysql_data_dev:/var/lib/mysql
    command: >
      --skip-character-set-client-handshake
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    networks:
      - net-mmt-dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  memento-minio-dev:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z-cpuv1
    container_name: memento-minio-dev
    ports:
      - "9010:9000"
      - "9011:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data_dev:/data
    command: server /data --console-address ":9001"
    networks:
      - net-mmt-dev
    healthcheck:
      test: ["CMD", "timeout", "5s", "bash", "-c", "</dev/tcp/localhost/9000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  minio-init-dev:
    image: minio/mc
    container_name: memento-minio-init-dev
    depends_on:
      - memento-minio-dev
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set dev http://memento-minio-dev:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
        mc mb dev/${POST_BUCKET} || true;
        mc mb dev/${VOICE_BUCKET} || true;
        mc mb dev/${EMOJI_BUCKET} || true;
        mc mb dev/${PROFILE_IMAGE_BUCKET} || true;
        mc anonymous set download dev/${POST_BUCKET};
        mc anonymous set download dev/${VOICE_BUCKET};
        mc anonymous set download dev/${EMOJI_BUCKET};
        mc anonymous set download dev/${PROFILE_IMAGE_BUCKET};
      "
    networks:
      - net-mmt-dev

  memento-redis-dev:
    image: redis:7.0
    container_name: memento-redis-dev
    restart: always
    ports:
      - "6381:6379"
    networks:
      - net-mmt-dev
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mysql_data_dev:
  minio_data_dev:

networks:
  net-mmt-dev:
