name: backend-ci

on:
  push:
    branches: ["develop", "main"]
    tags: ["v*"]
  pull_request:
    branches: ["develop", "main"]

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_dev:
    name: Build & Test (dev)
    runs-on: ubuntu-latest
    if: >
      github.ref == 'refs/heads/develop' ||
      (github.event_name == 'pull_request' && github.base_ref == 'develop')
    defaults:
      run:
        working-directory: memento

    steps:
      - uses: actions/checkout@v4

      - name: Ensure gradlew is executable
        run: chmod +x gradlew

      - name: Set up Java 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-root-directory: memento

      - name: Write Firebase service account (if provided)
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          mkdir -p src/main/resources
          if [ -n "${FIREBASE_CONFIG:-}" ]; then
            printf '%s' "${FIREBASE_CONFIG}" > src/main/resources/memento-serviceAccountKey.json
          else
            echo '{}' > src/main/resources/memento-serviceAccountKey.json
          fi

      - name: Build & test (bootJar → jar fallback)
        run: |
          ./gradlew clean bootJar --no-daemon -x test -x asciidoctor || ./gradlew clean jar --no-daemon -x test -x asciidoctor

      - name: Upload JAR (dev)
        uses: actions/upload-artifact@v4
        with:
          name: backend-dev
          path: memento/build/libs/*.jar
          retention-days: 14

  build_prod:
    name: Build & Test (prod)
    runs-on: ubuntu-latest
    if: >
      startsWith(github.ref, 'refs/heads/main') ||
      startsWith(github.ref, 'refs/tags/v') ||
      (github.event_name == 'pull_request' && github.base_ref == 'main')
    defaults:
      run:
        working-directory: memento

    steps:
      - uses: actions/checkout@v4
      - name: Ensure gradlew is executable
        run: chmod +x gradlew
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v3
        with:
          build-root-directory: memento

      - name: Write Firebase service account (if provided)
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          mkdir -p src/main/resources
          if [ -n "${FIREBASE_CONFIG:-}" ]; then
            printf '%s' "${FIREBASE_CONFIG}" > src/main/resources/memento-serviceAccountKey.json
          else
            echo '{}' > src/main/resources/memento-serviceAccountKey.json
          fi

      - name: Build (bootJar → jar fallback)
        run: |
          ./gradlew clean bootJar --no-daemon -x test -x asciidoctor || ./gradlew clean jar --no-daemon -x test -x asciidoctor
      - name: Upload JAR (prod)
        uses: actions/upload-artifact@v4
        with:
          name: backend-prod
          path: memento/build/libs/*.jar
          retention-days: 14
