name: backend-ci

on:
  push:
    branches: ["develop", "main"]
    tags: ["v*"]
  pull_request:
    branches: ["develop", "main"]

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_dev:
    name: Build & Test (dev)
    runs-on: ubuntu-latest
    if: >
      github.ref == 'refs/heads/develop' ||
      (github.event_name == 'pull_request' && github.base_ref == 'develop')

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v3
      - name: Build & test
        run: ./gradlew clean test war --no-daemon
      - name: Upload WAR (dev)
        uses: actions/upload-artifact@v4
        with:
          name: backend-dev
          path: build/libs/*.war
          retention-days: 14

  build_prod:
    name: Build & Test (prod)
    runs-on: ubuntu-latest
    if: >
      startsWith(github.ref, 'refs/heads/main') ||
      startsWith(github.ref, 'refs/tags/v') ||
      (github.event_name == 'pull_request' && github.base_ref == 'main')

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v3
      - name: Build & test
        run: ./gradlew clean test war --no-daemon
      - name: Upload WAR (prod)
        uses: actions/upload-artifact@v4
        with:
          name: backend-prod
          path: build/libs/*.war
          retention-days: 14
